name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/toltec-dev/base:v2.3

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake --preset release-toltec

      - name: Build
        run: cmake --build build/release-toltec

      - name: Package
        run: cmake --build build/release-toltec --target package

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/release-toltec/rm2stuff.ipk

      - name: Upload2
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/release-toltec/yaft

      - name: Upload3
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/release-toltec/yaft2

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download package
        id: download_package
        uses: actions/download-artifact@v2
        with:
          name: package
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
      - run: ls -la
      - name: Upload Release Package
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: rm2stuff.ipk
          asset_name: rm2stuff.ipk
          asset_content_type: application/gzip

      - name: Upload my Release Package
        id: upload-my-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: yaft
          asset_name: yaft
          asset_content_type: application/gzip

      - name: Upload my Release Package
        id: upload-my-release-asset2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: yaft2
          asset_name: yaft2
          asset_content_type: application/gzip


